const assert = require('assert');
const fs = require('fs');

const game = fs.readFileSync('./game.js', 'utf8');
const html = fs.readFileSync('./index.html', 'utf8');
const preview = fs.readFileSync('./character-preview.html', 'utf8');
const serviceWorker = fs.readFileSync('./sw.js', 'utf8');

assert.ok(game.includes('TowerData.getEnemyPool'));
assert.ok(game.includes('CombatVisualState.recordAttack'));
assert.ok(game.includes('CombatVisualState.recordHit'));
assert.ok(game.includes('CombatVisualState.recordSkill'));
assert.ok(game.includes('requestAnimationFrame(renderCombatFrame)'));
assert.ok(game.includes('CombatVisualState.pause'));
assert.ok(game.includes('CombatVisualState.resume'));
assert.ok(game.includes('state.lastEnemyHit+=pausedFor'));
assert.ok(game.includes('state.lastAttack+=pausedFor'));
assert.ok(game.includes('PixelArt.drawHero'));
assert.ok(game.includes('PixelArt.drawEnemy'));
assert.ok(game.includes('CombatLogic.recoverAfterFloor(state.hp,state.maxHp'));
assert.ok(game.includes('ascension.recovery'));
assert.ok(game.includes('state.lastFloorRecovery'));
assert.ok(game.includes('已恢复'));
assert.ok(game.includes('CombatVisualState.recordEnemyAttack'));
assert.ok(game.includes('weaponSkills'));
assert.ok(game.includes('renderSkillPicker'));
assert.ok(game.includes('resolveWeaponSkill'));
assert.ok(game.includes('getEnemyDamage'));
assert.ok(html.includes('skill-picker'));
assert.ok(game.includes('PixelArt.drawEnemyAttack'));
assert.ok(game.includes("effect.type==='enemy-attack'"));
assert.ok(html.indexOf('pixel-art.js?v=19') < html.indexOf('combat-visual-state.js?v=13'));
assert.ok(html.indexOf('combat-visual-state.js?v=13') < html.indexOf('game.js?v=21'));
assert.ok(serviceWorker.includes("ash-corridor-v38"));
assert.ok(serviceWorker.includes('self.skipWaiting()'));
assert.ok(serviceWorker.includes('self.clients.claim()'));
assert.ok(html.includes('pixel-art.js?v=19'));
assert.ok(html.includes('combat-visual-state.js?v=13'));
assert.ok(html.includes('game.js?v=21'));
assert.ok(html.includes('tower-data.js?v=1'));
assert.ok(html.includes('arena-backgrounds.js?v=2'));
assert.ok(html.includes('room-logic.js?v=1'));
assert.ok(serviceWorker.includes('result-flow.js?v=1'));
assert.ok(serviceWorker.includes('arena-backgrounds.js?v=2'));
assert.ok(serviceWorker.includes('room-logic.js?v=1'));
assert.ok(html.includes('build-system.js?v=1'));
assert.ok(serviceWorker.includes('build-system.js?v=1'));
assert.ok(game.includes('BuildSystem.getBuildState'));
assert.ok(game.includes('BuildSystem.getBuildBonuses'));
assert.ok(html.includes('build-pill'));
assert.ok(html.includes('skill-progression.js?v=1'));
assert.ok(serviceWorker.includes('skill-progression.js?v=1'));
assert.ok(game.includes('SkillProgression.getSkillEffect'));
assert.ok(game.includes('data-skill-choice'));
assert.ok(html.includes('boss-mechanics.js?v=1'));
assert.ok(serviceWorker.includes('boss-mechanics.js?v=2'));
assert.ok(game.includes('BossMechanics.createBossEvent'));
assert.ok(game.includes('drawBossMechanicSignal'));
assert.ok(html.includes('boss-mechanic-pill'));
assert.ok(html.includes('ascension.js?v=1'));
assert.ok(serviceWorker.includes('ascension.js?v=1'));
assert.ok(game.includes('Ascension.getAscensionModifiers'));
assert.ok(game.includes('cycleAscension'));
assert.ok(html.includes('ascension-btn'));
assert.ok(html.includes('achievements.js?v=1'));
assert.ok(serviceWorker.includes('achievements.js?v=1'));
assert.ok(game.includes('Achievements.evaluateRun'));
assert.ok(game.includes('renderCodex'));
assert.ok(html.includes('codex-screen'));
assert.ok(preview.includes('weapon:model.weapon||model.id'));
